### ISSUE TITLE
Bug première ligne scripts bash + amélioration logs

### ISSUE THREAD

**Issue by spyjo** [jeedom/plugin-script#22]
Hello,
J'avais fait un post sur le forum mais je pense qu'il est passé inaperçu, je remets mon message ici ça me semble plus approprié ;)
https://www.jeedom.com/forum/viewtopic.php?f=31&t=15219

"J'ai remarqué un soucis sur le script /core/ressources/isConnected.sh fourni par défaut avec le plugin , ainsi que sur d'autres dans le market des scripts, il manque parfois le point d'exclamation dans la première ligne du bash:

#/bin/bash
=>
#!/bin/bash

De ce fait, comme la ligne est invalide, le système prend par défaut "sh" plutot que "bash" pour exécuter le script, et ça peut rendre un script inopérant à cause des différences de syntaxes, sur les IF entre autre ("$str" == "yes" est valide en bash, pas en sh)

Je m'en suis rendu compte après avoir passé plus d'une heure à comprendre pourquoi un de mes scripts ne marchait qu'à moitié sur jeedom alors qu'il marchait bien en ligne de commande ... et j'avais malheureusement copié cette mauvaise ligne.

Et ça m'amène à autre chose, pour arriver à enfin comprendre le soucis de ce script, je me suis plongé dans le coeur du plugin script puis de jeedom pour rajouter des debugs, et je pense qu'une amélioration serait possible en ce sens:

Dans /core/com/shell.com.php , la variable $output n'est actuellement pas utilisée, il serait bien de la stocker dans $this->output , puis de créer une méthode getOutput() qui la return
pour ensuite dans le plugin script dans /plugin/script/class/script.class.php , ajouter dans les logs du script :
implode("\n", $request_shell->getOutput())
en supplément (ou remplacement) du log actuel qui n'est que la dernière ligne retournée, alors que là on a tout l'output du script (et donc toutes les erreurs qui vont avec) , ce qui m'aurait évité de perdre 2h  ^^ et à mon avis cela servira à d'autres qui ont des problèmes de scripts (ça m'étonnera pas d'ailleurs que le petit soucis sur la première ligne avec le "!" manquant en ait impacté plus d'un)"
_

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour, ca sera pris en compte dans jeedom 2.0 (correction pour le retour des exécutions des scripts)
